[theme]
primary = "#abb2bf"
secondary = "yellow"
title = "blue"
playing = "green"
playing_selected = "yellow"
highlight = "yellow"
highlight_bg = "default"
error_bg = "red"
statusbar_progress = "green"
statusbar = "green"
statusbar_bg = "default"
cmdline = "default"
cmdline_bg = "default"
search_match = "light red"

[saved_state]
volume = 70
